### ISSUE TITLE
Enhance drag and drop functionality

### ISSUE THREAD

**Issue by bigardone** [bigardone/phoenix-trello#1]
Even though drag and drop works fine I still have to find a way of adding drop placeholders so the user sees where the draggable item is going to be dropped having in mind that state is managed with Redux.

**Comment by chrislaskey** [comment]
I just posted PR https://github.com/bigardone/phoenix-trello/pull/30 with a CSS based enhancement to show a placeholder when dragging cards within the same list and between lists.

Thanks again for the excellent code and tutorial text, it's great to see a non trivial example built step by step 😃

**Comment by bigardone** [comment]
Hey @chrislaskey I'm glad you liked it! And thank you very much for taking care of this, I just made a minor suggestion before merging it :)
Cheers!!!
