### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Everhusk** [bigardone/phoenix-trello#17]
Keep getting this error when running locally (Phoenix v1.1.2):

```
== Compilation error on file lib/phoenix_trello/guardian_serializer.ex ==
** (SyntaxError) lib/phoenix_trello/guardian_serializer.ex:4: syntax error before: '{'
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by Everhusk** [comment]
Looks like 

` alias PhoenixTrello.{Repo,User}`

needs to be split into

` alias PhoenixTrello.Repo 
  alias PhoenixTrello.User`

**Comment by wuming123057** [comment]
From Elixir v1.2  it is possible to alias, import or require multiple modules at once.
So your Elixir version must  be 1.2 or more.
Refer to [Multi alias/import/require/use](http://elixir-lang.org/getting-started/alias-require-and-import.html)

**Comment by bigardone** [comment]
Yeah, you're totally right. The project is assuming that you have Elixir 1.2 installed. I'll add it in the readme file :)
Thanks!
