### ISSUE TITLE
Demo account for login

### ISSUE THREAD

**Issue by winkler1** [bigardone/phoenix-trello#2]
Hi Ricardo-
 Thanks for sending this to React.rocks! I'm excited about Elixir/Phoenix.
 One concern: having a user login will probably cause 99% of people to drop off. Some possible options--
1) auto-log in under a fake account for demo purposes
2) Seed the edit boxes with username/pass, so they just click "Sign In"
3) Have text on page telling user name/pass

Options 1 or 2 would be ideal :)
Thanks, I'm putting this project on my reading list,
Jeff

**Comment by bigardone** [comment]
Hey @winkler1, thank you for your words, you're totally right. I'm going to implement the first and second options right now :)

**Comment by bigardone** [comment]
Done! Thanks again :)
