### ISSUE TITLE
error on file lib/phoenix_trello/guardian_serializer.ex

### ISSUE THREAD

**Issue by araslanov-e** [bigardone/phoenix-trello#20]
== Compilation error on file lib/phoenix_trello/guardian_serializer.ex ==
** (SyntaxError) lib/phoenix_trello/guardian_serializer.ex:4: syntax error before: '{'
    (elixir) lib/kernel/parallel_compiler.ex: 100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by araslanov-e** [comment]
$ elixir -v
Elixir 1.1.1

**Comment by bigardone** [comment]
Hi @araslanov-e 
You need to have Elixir 1.2 at least.

https://github.com/bigardone/phoenix-trello#requirements

Cheers

**Comment by araslanov-e** [comment]
:+1:
