### ISSUE TITLE
Error on step 2, addLocal Could not install phoenix_trello/deps/phoenix

### ISSUE THREAD

**Issue by sergiotapia** [bigardone/phoenix-trello#23]
Copied your package.json file from here: https://github.com/bigardone/phoenix-trello/blob/master/package.json

```
sergiotapia at Sergios-iMac in ~/Work/phoenix_trello on master [?]
$ npm install
npm ERR! addLocal Could not install /Users/sergiotapia/Work/phoenix_trello/deps/phoenix
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sergiotapia/Work/phoenix_trello/npm-debug.log
```

**Comment by bigardone** [comment]
Hi Sergio :)
I think your `npm` and `node` versions are too old, I'm using the following:

- **npm**: 3.5.2
- **node**: 5.3.0

Upgrading them will do the trick.

**Comment by muneef** [comment]
Tried this with 
npm  v3.9.0
node v5.5.0

Still can't get over it

**Comment by alex88** [comment]
@sergiotapia @muneef are you sure to have the phoenix dependencies installed? Seems npm is trying to install the phoenix package which, after installing phoenix dependencies, is inside the deps folder
