### ISSUE TITLE
SumoMe / Google Analytics

### ISSUE THREAD

**Issue by simondelacourt** [bigardone/phoenix-trello#33]
The example contains tracking from SumoMe and Google, might be nice to remove that or state it in the readme, as most people whitelist their localhosts.. I don't mind having tracking on the live example, as I by default would block it, but having this in an example that you'd run on localhost seems a bit awkward.

**Comment by bigardone** [comment]
Oh my, I thought I did it just on my deployment branch... Sorry about that, and thanks for notifying :)
