### ISSUE TITLE
update Devs  to latest

### ISSUE THREAD

**Issue by mydearxym** [bigardone/phoenix-trello#35]
amazing work!
since elixir 1.3 and phoenix 1.2 is released , maybe time to update the devs to keep it sharp

**Comment by aislanmaia** [comment]
I'm following the tutorial right now, and it's getting hard to keeping going with latest, then I second this desire for update. : )

**Comment by bigardone** [comment]
Yeah, I agree too. I'll do the upgrade as soon as I have some time to work on it.

**Comment by bigardone** [comment]
Hi @aislanmaia !
I have finally managed to find some time to upgrade the repo and tutorial 🎉 
Cheers!

**Comment by aislanmaia** [comment]
This is awesome!! All the things are working as expected? I'm looking forward to check this out...
Thanks!

**Comment by bigardone** [comment]
You're welcome! The live demo has this version and everything working as expected ;)
Cheers!
