### ISSUE TITLE
error on create and migrate database

### ISSUE THREAD

**Issue by marulitua** [bigardone/phoenix-trello#36]
I tried to follow the installation instructions but it error when i tried to run
`mix ecto.create && mix ecto.migrate`
with the following message
Compiling 34 files (.ex)
warning: unused alias Repo
  web/models/board.ex:5

== Compilation error on file web/router.ex ==
** (CompileError) web/router.ex: internal error in v3_core;
crash reason: {case_clause,
    {'EXIT',
        {badarg,
            [{erl_anno,anno_info,[-1],[{file,"erl_anno.erl"},{line,360}]},
             {v3_core,record_anno,2,[{file,"v3_core.erl"},{line,2410}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,539}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,528}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,538}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,538}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,528}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,652}]},
             {v3_core,exprs,2,[{file,"v3_core.erl"},{line,512}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/2 (compile.erl, line 530)
  in call from compile:'-internal_comp/4-anonymous-1-'/2 (compile.erl, line 315)
  in call from compile:fold_comp/3 (compile.erl, line 341)
  in call from compile:internal_comp/4 (compile.erl, line 325)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 175)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (phoenix) expanding macro: Phoenix.Router.__before_compile__/1
    web/router.ex:1: PhoenixTrello.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

**I am on**
Arch Linux 
Erlang 19
Elixir 1.3.2

**Additional info**
I don't know if this is relevant, at first i have to update jose dependency.
==> jose
Compiling 72 files (.erl)
compile: warnings being treated as errors
src/jose_jwe_alg_aes_kw.erl:103: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
compile: warnings being treated as errors
src/jose_jwk_kty.erl:198: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
compile: warnings being treated as errors
src/jose_jwk_kty_ec.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_kty_okp_ed25519.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_kty_okp_ed25519ph.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_kty_okp_ed448.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_kty_okp_x25519.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_kty_okp_x448.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_kty_rsa.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_pem.erl:40: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
compile: warnings being treated as errors
src/jose_jwa_pkcs1.erl:267: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/jose_jwa_pkcs1.erl:416: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/jose_jwa_pkcs1.erl:605: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
compile: warnings being treated as errors
src/jose_jwe_alg_pbes2.erl:73: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
compile: warnings being treated as errors
src/jose_jwe_enc_aes.erl:198: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/jose_jwe_enc_aes.erl:201: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
compile: warnings being treated as errors
src/jose_jwk_kty_okp_ed448ph.erl:13: behaviour jose_jwk_kty undefined
compile: warnings being treated as errors
src/jose_jwk_kty_oct.erl:13: behaviour jose_jwk_kty undefined
src/jose_jwk_kty_oct.erl:91: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
could not compile dependency :jose, "mix compile" failed. You can recompile this dependency with "mix deps.compile jose", update it with "mix deps.update jose" or clean it with "mix deps.clean jose"
==> phoenix_trello
** (Mix) Encountered compilation errors
In orde to get rid of this error i run 
`mix deps.update jose`

**Comment by daniel1943** [comment]
Same os/erlang/elixir, same problem :) Thanks for adding quick solution.

**Comment by BazzalSeed** [comment]
still getting the same problem after running  mix deps.update jose

any ideas?

**Comment by marulitua** [comment]
guys we need to update phoenix_html and phoenix it self.
Please run the following
`mix deps.update phoenix_html`
`mix deps.update phoenix`
then you are good to go.
By the way i found this issue have been solved on https://elixirforum.com/t/erlang-19-0-elixir-1-3-and-phoenix-1-1-4-compatible/911/6
