### ISSUE TITLE
Confusion about the phoenix.js file

### ISSUE THREAD

**Issue by timuckun** [bigardone/phoenix-trello#37]
In the tutorial it says.

There is just one more thing to do here. If we look into the private/static/js folder we will find a phoenix.js file. This file contains everything we need to use websockets and their channels, so let's move it to our base source folder web/static/js so we can require it wherever we may need it.

First of all that should be /priv/static/js (minor nit) but when I look at the source code there is no phoenix.js in the web/static/js or priv/static/js. Where did it go? I see an application.js there but it looks nothing like phoenix.js

Thanks

**Comment by bigardone** [comment]
Hi @timuckun !
Sorry about the confusion. The tutorial and project were made with an older version of Phoenix.
In the latest version you have to include both phoenix js packages in the `package.json` file like this:

``` json
"phoenix": "file:deps/phoenix",
"phoenix_html": "file:deps/phoenix_html",
```

I have updated the project and tutorial, so nobody has the same issue.
Cheers!
