### ISSUE TITLE
Live demo not working!

### ISSUE THREAD

**Issue by aadrian** [bigardone/phoenix-trello#38]
The live demo does not seem to work anymore.

I'm getting:
```

Application Error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

```

**Comment by bigardone** [comment]
Hi @aadrian !
The problem is that the demo is hosted in a free Heroku app, and as it has so much traffic it has already exceeded the free hours limit. It will be available again next month, in the meantime, I have to find a better place to host it :(
Cheers!
